//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlertApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have accept.
        /// </summary>
        internal static string AcceptedFromMe {
            get {
                return ResourceManager.GetString("AcceptedFromMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contacts.
        /// </summary>
        internal static string AddContactsPage {
            get {
                return ResourceManager.GetString("AddContactsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send request to selected contacts?.
        /// </summary>
        internal static string AlertAddContactsMessage {
            get {
                return ResourceManager.GetString("AlertAddContactsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contacts.
        /// </summary>
        internal static string AlertAddContactsTitle {
            get {
                return ResourceManager.GetString("AlertAddContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        internal static string AlertSosTitle {
            get {
                return ResourceManager.GetString("AlertSosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allways On.
        /// </summary>
        internal static string AllwaysOn {
            get {
                return ResourceManager.GetString("AllwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert 24/7.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackRegistration {
            get {
                return ResourceManager.GetString("BackRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string BlockedUsersPage {
            get {
                return ResourceManager.GetString("BlockedUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string BlockRequest {
            get {
                return ResourceManager.GetString("BlockRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block this user.
        /// </summary>
        internal static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user will be no longer be able to contact you....
        /// </summary>
        internal static string BlockUserSubtitle {
            get {
                return ResourceManager.GetString("BlockUserSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By accepting.
        /// </summary>
        internal static string ByAccepting {
            get {
                return ResourceManager.GetString("ByAccepting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be able to alert you via this app whenever he&apos;s in need of help.
        /// </summary>
        internal static string ByAcceptingWillAbleToHelpYou {
            get {
                return ResourceManager.GetString("ByAcceptingWillAbleToHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to cancel.
        /// </summary>
        internal static string CancelSendAlert {
            get {
                return ResourceManager.GetString("CancelSendAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Community Request.
        /// </summary>
        internal static string CommunityRequestPage {
            get {
                return ResourceManager.GetString("CommunityRequestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueDialogButton {
            get {
                return ResourceManager.GetString("ContinueDialogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention : Don&apos;t use OTP code as pin.
        /// </summary>
        internal static string DontUseOtpAsPinMessage {
            get {
                return ResourceManager.GetString("DontUseOtpAsPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pin.
        /// </summary>
        internal static string EnterApplicationPinTitle {
            get {
                return ResourceManager.GetString("EnterApplicationPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile number.
        /// </summary>
        internal static string EnterMobileDialogMessage {
            get {
                return ResourceManager.GetString("EnterMobileDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mobile.
        /// </summary>
        internal static string EnterMobileDialogTitle {
            get {
                return ResourceManager.GetString("EnterMobileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your mobile number to receive a verification code by SMS..
        /// </summary>
        internal static string EnterMobileMessage {
            get {
                return ResourceManager.GetString("EnterMobileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mobile.
        /// </summary>
        internal static string EnterMobileNumberTitle {
            get {
                return ResourceManager.GetString("EnterMobileNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Number.
        /// </summary>
        internal static string EnterMobilePrompt {
            get {
                return ResourceManager.GetString("EnterMobilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter application pin.
        /// </summary>
        internal static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER PIN TO CANCEL.
        /// </summary>
        internal static string EnterPinToCancel {
            get {
                return ResourceManager.GetString("EnterPinToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string EnterVerificationCodeTitle {
            get {
                return ResourceManager.GetString("EnterVerificationCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishRegistration {
            get {
                return ResourceManager.GetString("FinishRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGNORE.
        /// </summary>
        internal static string IgnoreHelp {
            get {
                return ResourceManager.GetString("IgnoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreRequest {
            get {
                return ResourceManager.GetString("IgnoreRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVITE.
        /// </summary>
        internal static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I WILL HELP.
        /// </summary>
        internal static string IWillHelp {
            get {
                return ResourceManager.GetString("IWillHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are off. Please open it in order to keep you safe..
        /// </summary>
        internal static string LocationServicesOffMessage {
            get {
                return ResourceManager.GetString("LocationServicesOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Tracking.
        /// </summary>
        internal static string LocationTracking {
            get {
                return ResourceManager.GetString("LocationTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contacts.
        /// </summary>
        internal static string ManageContacts {
            get {
                return ResourceManager.GetString("ManageContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Community Request.
        /// </summary>
        internal static string NewCommunityRequestTitlePage {
            get {
                return ResourceManager.GetString("NewCommunityRequestTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wants you to participate in his community!.
        /// </summary>
        internal static string NewCommunityRequestWantParticipateMessage {
            get {
                return ResourceManager.GetString("NewCommunityRequestWantParticipateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextRegistration {
            get {
                return ResourceManager.GetString("NextRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts found.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter information needed.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this user.
        /// </summary>
        internal static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user will be removed, but you can still....
        /// </summary>
        internal static string RemoveUserSubtitle {
            get {
                return ResourceManager.GetString("RemoveUserSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Code.
        /// </summary>
        internal static string ResendCodeButton {
            get {
                return ResourceManager.GetString("ResendCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Radius.
        /// </summary>
        internal static string SafetyRadius {
            get {
                return ResourceManager.GetString("SafetyRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchBarPlaceHolder {
            get {
                return ResourceManager.GetString("SearchBarPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select application language.
        /// </summary>
        internal static string SelectLanguageMessage {
            get {
                return ResourceManager.GetString("SelectLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select position.
        /// </summary>
        internal static string SelectPositionFromMapPage {
            get {
                return ResourceManager.GetString("SelectPositionFromMapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending alert.
        /// </summary>
        internal static string SendingAlert {
            get {
                return ResourceManager.GetString("SendingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending alert in.
        /// </summary>
        internal static string SendingAlertIn {
            get {
                return ResourceManager.GetString("SendingAlertIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via.
        /// </summary>
        internal static string ShareVia {
            get {
                return ResourceManager.GetString("ShareVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code will be send to .
        /// </summary>
        internal static string SmsVerificationMessage {
            get {
                return ResourceManager.GetString("SmsVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact added successfully..
        /// </summary>
        internal static string SuccessAddContactMessage {
            get {
                return ResourceManager.GetString("SuccessAddContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessAddContactTitle {
            get {
                return ResourceManager.GetString("SuccessAddContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependands.
        /// </summary>
        internal static string TabDependands {
            get {
                return ResourceManager.GetString("TabDependands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My community.
        /// </summary>
        internal static string TabMyCommunity {
            get {
                return ResourceManager.GetString("TabMyCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string TabSuggestions {
            get {
                return ResourceManager.GetString("TabSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location permission.
        /// </summary>
        internal static string UnableToGetLocationPermission {
            get {
                return ResourceManager.GetString("UnableToGetLocationPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for OTP message.. When SMS received, app will activated automatically.
        /// </summary>
        internal static string WaitForSMS {
            get {
                return ResourceManager.GetString("WaitForSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please with....
        /// </summary>
        internal static string WaitForSmsMessage {
            get {
                return ResourceManager.GetString("WaitForSmsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile number.
        /// </summary>
        internal static string WarningFillNumber {
            get {
                return ResourceManager.GetString("WarningFillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter application PIN.
        /// </summary>
        internal static string WarningFillPin {
            get {
                return ResourceManager.GetString("WarningFillPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Alert247.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who alerts me.
        /// </summary>
        internal static string WhoAlertMe {
            get {
                return ResourceManager.GetString("WhoAlertMe", resourceCulture);
            }
        }
    }
}
