//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertApp.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlertApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AllwaysOn {
            get {
                return ResourceManager.GetString("AllwaysOn", resourceCulture);
            }
        }
        
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string BackRegistration {
            get {
                return ResourceManager.GetString("BackRegistration", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string CancelSendAlert {
            get {
                return ResourceManager.GetString("CancelSendAlert", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string ContinueDialogButton {
            get {
                return ResourceManager.GetString("ContinueDialogButton", resourceCulture);
            }
        }
        
        internal static string EnterApplicationPinTitle {
            get {
                return ResourceManager.GetString("EnterApplicationPinTitle", resourceCulture);
            }
        }
        
        internal static string EnterMobileMessage {
            get {
                return ResourceManager.GetString("EnterMobileMessage", resourceCulture);
            }
        }
        
        internal static string EnterMobileNumberTitle {
            get {
                return ResourceManager.GetString("EnterMobileNumberTitle", resourceCulture);
            }
        }
        
        internal static string EnterMobilePrompt {
            get {
                return ResourceManager.GetString("EnterMobilePrompt", resourceCulture);
            }
        }
        
        internal static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        internal static string EnterPinToCancel {
            get {
                return ResourceManager.GetString("EnterPinToCancel", resourceCulture);
            }
        }
        
        internal static string EnterVerificationCodeTitle {
            get {
                return ResourceManager.GetString("EnterVerificationCodeTitle", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string FinishRegistration {
            get {
                return ResourceManager.GetString("FinishRegistration", resourceCulture);
            }
        }
        
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        internal static string LocationTracking {
            get {
                return ResourceManager.GetString("LocationTracking", resourceCulture);
            }
        }
        
        internal static string ManageContacts {
            get {
                return ResourceManager.GetString("ManageContacts", resourceCulture);
            }
        }
        
        internal static string NextRegistration {
            get {
                return ResourceManager.GetString("NextRegistration", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        internal static string ResendCodeButton {
            get {
                return ResourceManager.GetString("ResendCodeButton", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string SelectLanguageMessage {
            get {
                return ResourceManager.GetString("SelectLanguageMessage", resourceCulture);
            }
        }
        
        internal static string SendingAlertIn {
            get {
                return ResourceManager.GetString("SendingAlertIn", resourceCulture);
            }
        }
        
        internal static string SmsVerificationMessage {
            get {
                return ResourceManager.GetString("SmsVerificationMessage", resourceCulture);
            }
        }
        
        internal static string TabDependands {
            get {
                return ResourceManager.GetString("TabDependands", resourceCulture);
            }
        }
        
        internal static string TabMyCommunity {
            get {
                return ResourceManager.GetString("TabMyCommunity", resourceCulture);
            }
        }
        
        internal static string TabSuggestions {
            get {
                return ResourceManager.GetString("TabSuggestions", resourceCulture);
            }
        }
        
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        internal static string WaitForSMS {
            get {
                return ResourceManager.GetString("WaitForSMS", resourceCulture);
            }
        }
        
        internal static string WaitForSmsMessage {
            get {
                return ResourceManager.GetString("WaitForSmsMessage", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string WarningFillNumber {
            get {
                return ResourceManager.GetString("WarningFillNumber", resourceCulture);
            }
        }
        
        internal static string WarningFillPin {
            get {
                return ResourceManager.GetString("WarningFillPin", resourceCulture);
            }
        }
        
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string WhoAlertMe {
            get {
                return ResourceManager.GetString("WhoAlertMe", resourceCulture);
            }
        }
        
        internal static string AddContactsPage {
            get {
                return ResourceManager.GetString("AddContactsPage", resourceCulture);
            }
        }
        
        internal static string AlertAddContactsMessage {
            get {
                return ResourceManager.GetString("AlertAddContactsMessage", resourceCulture);
            }
        }
        
        internal static string AlertAddContactsTitle {
            get {
                return ResourceManager.GetString("AlertAddContactsTitle", resourceCulture);
            }
        }
        
        internal static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        internal static string ShareVia {
            get {
                return ResourceManager.GetString("ShareVia", resourceCulture);
            }
        }
        
        internal static string EnterMobileDialogMessage {
            get {
                return ResourceManager.GetString("EnterMobileDialogMessage", resourceCulture);
            }
        }
        
        internal static string EnterMobileDialogTitle {
            get {
                return ResourceManager.GetString("EnterMobileDialogTitle", resourceCulture);
            }
        }
        
        internal static string SafetyRadius {
            get {
                return ResourceManager.GetString("SafetyRadius", resourceCulture);
            }
        }
        
        internal static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        internal static string BlockRequest {
            get {
                return ResourceManager.GetString("BlockRequest", resourceCulture);
            }
        }
        
        internal static string CommunityRequestPage {
            get {
                return ResourceManager.GetString("CommunityRequestPage", resourceCulture);
            }
        }
        
        internal static string IgnoreRequest {
            get {
                return ResourceManager.GetString("IgnoreRequest", resourceCulture);
            }
        }
        
        internal static string SelectPositionFromMapPage {
            get {
                return ResourceManager.GetString("SelectPositionFromMapPage", resourceCulture);
            }
        }
        
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        internal static string UnableToGetLocationPermission {
            get {
                return ResourceManager.GetString("UnableToGetLocationPermission", resourceCulture);
            }
        }
        
        internal static string NewCommunityRequestTitlePage {
            get {
                return ResourceManager.GetString("NewCommunityRequestTitlePage", resourceCulture);
            }
        }
        
        internal static string ByAccepting {
            get {
                return ResourceManager.GetString("ByAccepting", resourceCulture);
            }
        }
        
        internal static string ByAcceptingWillAbleToHelpYou {
            get {
                return ResourceManager.GetString("ByAcceptingWillAbleToHelpYou", resourceCulture);
            }
        }
        
        internal static string NewCommunityRequestWantParticipateMessage {
            get {
                return ResourceManager.GetString("NewCommunityRequestWantParticipateMessage", resourceCulture);
            }
        }
        
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        internal static string IgnoreHelp {
            get {
                return ResourceManager.GetString("IgnoreHelp", resourceCulture);
            }
        }
        
        internal static string IWillHelp {
            get {
                return ResourceManager.GetString("IWillHelp", resourceCulture);
            }
        }
        
        internal static string AlertSosTitle {
            get {
                return ResourceManager.GetString("AlertSosTitle", resourceCulture);
            }
        }
        
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        internal static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        internal static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        internal static string BlockUserSubtitle {
            get {
                return ResourceManager.GetString("BlockUserSubtitle", resourceCulture);
            }
        }
        
        internal static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        internal static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        internal static string RemoveUserSubtitle {
            get {
                return ResourceManager.GetString("RemoveUserSubtitle", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceHolder {
            get {
                return ResourceManager.GetString("SearchBarPlaceHolder", resourceCulture);
            }
        }
        
        internal static string SuccessAddContactMessage {
            get {
                return ResourceManager.GetString("SuccessAddContactMessage", resourceCulture);
            }
        }
        
        internal static string SuccessAddContactTitle {
            get {
                return ResourceManager.GetString("SuccessAddContactTitle", resourceCulture);
            }
        }
        
        internal static string SendingAlert {
            get {
                return ResourceManager.GetString("SendingAlert", resourceCulture);
            }
        }
        
        internal static string BlockedUsersPage {
            get {
                return ResourceManager.GetString("BlockedUsersPage", resourceCulture);
            }
        }
        
        internal static string AcceptedFromMe {
            get {
                return ResourceManager.GetString("AcceptedFromMe", resourceCulture);
            }
        }
        
        internal static string DontUseOtpAsPinMessage {
            get {
                return ResourceManager.GetString("DontUseOtpAsPinMessage", resourceCulture);
            }
        }
        
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        internal static string LocationServicesOffMessage {
            get {
                return ResourceManager.GetString("LocationServicesOffMessage", resourceCulture);
            }
        }
        
        internal static string SuccessSendAlert {
            get {
                return ResourceManager.GetString("SuccessSendAlert", resourceCulture);
            }
        }
        
        internal static string SuccessSendAlertMessage {
            get {
                return ResourceManager.GetString("SuccessSendAlertMessage", resourceCulture);
            }
        }
        
        internal static string SuccessSendAlertMessageContacts {
            get {
                return ResourceManager.GetString("SuccessSendAlertMessageContacts", resourceCulture);
            }
        }
        
        internal static string TheAlert {
            get {
                return ResourceManager.GetString("TheAlert", resourceCulture);
            }
        }
        
        internal static string Accident {
            get {
                return ResourceManager.GetString("Accident", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        internal static string Threat {
            get {
                return ResourceManager.GetString("Threat", resourceCulture);
            }
        }
        
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        internal static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        internal static string EmergencyAlertText {
            get {
                return ResourceManager.GetString("EmergencyAlertText", resourceCulture);
            }
        }
        
        internal static string EnterPinFor {
            get {
                return ResourceManager.GetString("EnterPinFor", resourceCulture);
            }
        }
        
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        internal static string Medecine {
            get {
                return ResourceManager.GetString("Medecine", resourceCulture);
            }
        }
        
        internal static string NewAlertTitle {
            get {
                return ResourceManager.GetString("NewAlertTitle", resourceCulture);
            }
        }
        
        internal static string PressedAlert {
            get {
                return ResourceManager.GetString("PressedAlert", resourceCulture);
            }
        }
        
        internal static string SendAlertTitle {
            get {
                return ResourceManager.GetString("SendAlertTitle", resourceCulture);
            }
        }
        
        internal static string SendingAlertToSelectedContacts {
            get {
                return ResourceManager.GetString("SendingAlertToSelectedContacts", resourceCulture);
            }
        }
        
        internal static string UserIsInPosition {
            get {
                return ResourceManager.GetString("UserIsInPosition", resourceCulture);
            }
        }
        
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        internal static string AcceptContactRequest {
            get {
                return ResourceManager.GetString("AcceptContactRequest", resourceCulture);
            }
        }
        
        internal static string ContactRequestText {
            get {
                return ResourceManager.GetString("ContactRequestText", resourceCulture);
            }
        }
        
        internal static string IgnoreContactRequest {
            get {
                return ResourceManager.GetString("IgnoreContactRequest", resourceCulture);
            }
        }
        
        internal static string NewContactRequestTitle {
            get {
                return ResourceManager.GetString("NewContactRequestTitle", resourceCulture);
            }
        }
        
        internal static string StartSettings {
            get {
                return ResourceManager.GetString("StartSettings", resourceCulture);
            }
        }
        
        internal static string VerificationCodePageTitle {
            get {
                return ResourceManager.GetString("VerificationCodePageTitle", resourceCulture);
            }
        }
        
        internal static string LocationTrackingExplanation {
            get {
                return ResourceManager.GetString("LocationTrackingExplanation", resourceCulture);
            }
        }
        
        internal static string RegistrationEnterPinPromt {
            get {
                return ResourceManager.GetString("RegistrationEnterPinPromt", resourceCulture);
            }
        }
        
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        internal static string RegistrationEnterFieldsPromt {
            get {
                return ResourceManager.GetString("RegistrationEnterFieldsPromt", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string NoAlertRecipients {
            get {
                return ResourceManager.GetString("NoAlertRecipients", resourceCulture);
            }
        }
        
        internal static string RegistrationCreatePinPromt {
            get {
                return ResourceManager.GetString("RegistrationCreatePinPromt", resourceCulture);
            }
        }
        
        internal static string MainPressToCancel {
            get {
                return ResourceManager.GetString("MainPressToCancel", resourceCulture);
            }
        }
        
        internal static string InviteFriendsSubtitle {
            get {
                return ResourceManager.GetString("InviteFriendsSubtitle", resourceCulture);
            }
        }
        
        internal static string InviteFriendsTitle {
            get {
                return ResourceManager.GetString("InviteFriendsTitle", resourceCulture);
            }
        }
        
        internal static string SelectContact {
            get {
                return ResourceManager.GetString("SelectContact", resourceCulture);
            }
        }
        
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        internal static string medicine {
            get {
                return ResourceManager.GetString("medicine", resourceCulture);
            }
        }
        
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        internal static string AddContactMenu {
            get {
                return ResourceManager.GetString("AddContactMenu", resourceCulture);
            }
        }
        
        internal static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        internal static string ShareMessageTitle {
            get {
                return ResourceManager.GetString("ShareMessageTitle", resourceCulture);
            }
        }
        
        internal static string SettingChangePin {
            get {
                return ResourceManager.GetString("SettingChangePin", resourceCulture);
            }
        }
        
        internal static string SettingContacts {
            get {
                return ResourceManager.GetString("SettingContacts", resourceCulture);
            }
        }
        
        internal static string SettingEnviroment {
            get {
                return ResourceManager.GetString("SettingEnviroment", resourceCulture);
            }
        }
        
        internal static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        internal static string SettingLanguageSubTitle {
            get {
                return ResourceManager.GetString("SettingLanguageSubTitle", resourceCulture);
            }
        }
        
        internal static string SettingLanguageTitle {
            get {
                return ResourceManager.GetString("SettingLanguageTitle", resourceCulture);
            }
        }
        
        internal static string SettingLocation {
            get {
                return ResourceManager.GetString("SettingLocation", resourceCulture);
            }
        }
        
        internal static string SettingsAccount {
            get {
                return ResourceManager.GetString("SettingsAccount", resourceCulture);
            }
        }
        
        internal static string SettingsPermissions {
            get {
                return ResourceManager.GetString("SettingsPermissions", resourceCulture);
            }
        }
        
        internal static string SettingsView {
            get {
                return ResourceManager.GetString("SettingsView", resourceCulture);
            }
        }
        
        internal static string SettingButtonsSubTitle {
            get {
                return ResourceManager.GetString("SettingButtonsSubTitle", resourceCulture);
            }
        }
        
        internal static string SettingButtonsTitle {
            get {
                return ResourceManager.GetString("SettingButtonsTitle", resourceCulture);
            }
        }
        
        internal static string SettingsButtonsViewMessage {
            get {
                return ResourceManager.GetString("SettingsButtonsViewMessage", resourceCulture);
            }
        }
        
        internal static string SwitchAccident {
            get {
                return ResourceManager.GetString("SwitchAccident", resourceCulture);
            }
        }
        
        internal static string SwitchFire {
            get {
                return ResourceManager.GetString("SwitchFire", resourceCulture);
            }
        }
        
        internal static string SwitchTreat {
            get {
                return ResourceManager.GetString("SwitchTreat", resourceCulture);
            }
        }
        
        internal static string SwitchContacts {
            get {
                return ResourceManager.GetString("SwitchContacts", resourceCulture);
            }
        }
        
        internal static string SwitchInformation {
            get {
                return ResourceManager.GetString("SwitchInformation", resourceCulture);
            }
        }
        
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        internal static string ConfirmPinToSaveSettings {
            get {
                return ResourceManager.GetString("ConfirmPinToSaveSettings", resourceCulture);
            }
        }
        
        internal static string SettingPermissionLocationSubTitle {
            get {
                return ResourceManager.GetString("SettingPermissionLocationSubTitle", resourceCulture);
            }
        }
        
        internal static string SettingPermissionTitle {
            get {
                return ResourceManager.GetString("SettingPermissionTitle", resourceCulture);
            }
        }
        
        internal static string SettingsLocationMessage {
            get {
                return ResourceManager.GetString("SettingsLocationMessage", resourceCulture);
            }
        }
        
        internal static string SettingsLocationSubtitle {
            get {
                return ResourceManager.GetString("SettingsLocationSubtitle", resourceCulture);
            }
        }
        
        internal static string ContactPermissionSetting {
            get {
                return ResourceManager.GetString("ContactPermissionSetting", resourceCulture);
            }
        }
        
        internal static string ContactPermissionSettingTitle {
            get {
                return ResourceManager.GetString("ContactPermissionSettingTitle", resourceCulture);
            }
        }
        
        internal static string SettingsContactsPermissionSubtitle {
            get {
                return ResourceManager.GetString("SettingsContactsPermissionSubtitle", resourceCulture);
            }
        }
        
        internal static string SettingAccountTitle {
            get {
                return ResourceManager.GetString("SettingAccountTitle", resourceCulture);
            }
        }
        
        internal static string SettingsChangePinMessage {
            get {
                return ResourceManager.GetString("SettingsChangePinMessage", resourceCulture);
            }
        }
        
        internal static string EnterNewPin {
            get {
                return ResourceManager.GetString("EnterNewPin", resourceCulture);
            }
        }
        
        internal static string ReEnterNewPin {
            get {
                return ResourceManager.GetString("ReEnterNewPin", resourceCulture);
            }
        }
        
        internal static string ContactsPermissionActive {
            get {
                return ResourceManager.GetString("ContactsPermissionActive", resourceCulture);
            }
        }
        
        internal static string ContactsPermissionInActive {
            get {
                return ResourceManager.GetString("ContactsPermissionInActive", resourceCulture);
            }
        }
        
        internal static string Succcess {
            get {
                return ResourceManager.GetString("Succcess", resourceCulture);
            }
        }
        
        internal static string SucccessChangePinMessage {
            get {
                return ResourceManager.GetString("SucccessChangePinMessage", resourceCulture);
            }
        }
        
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        internal static string DevelopedFor {
            get {
                return ResourceManager.GetString("DevelopedFor", resourceCulture);
            }
        }
        
        internal static string PrivacyTerms {
            get {
                return ResourceManager.GetString("PrivacyTerms", resourceCulture);
            }
        }
        
        internal static string WrongPin {
            get {
                return ResourceManager.GetString("WrongPin", resourceCulture);
            }
        }
        
        internal static string AlwaysOnCaps {
            get {
                return ResourceManager.GetString("AlwaysOnCaps", resourceCulture);
            }
        }
        
        internal static string DeleteAccountHistory {
            get {
                return ResourceManager.GetString("DeleteAccountHistory", resourceCulture);
            }
        }
        
        internal static string DownloadAccountHistory {
            get {
                return ResourceManager.GetString("DownloadAccountHistory", resourceCulture);
            }
        }
        
        internal static string SettingDeleteAccount {
            get {
                return ResourceManager.GetString("SettingDeleteAccount", resourceCulture);
            }
        }
        
        internal static string SettingHistory {
            get {
                return ResourceManager.GetString("SettingHistory", resourceCulture);
            }
        }
        
        internal static string SettingsAccountHistoryMessage {
            get {
                return ResourceManager.GetString("SettingsAccountHistoryMessage", resourceCulture);
            }
        }
        
        internal static string DeleteAccountMessageAlert {
            get {
                return ResourceManager.GetString("DeleteAccountMessageAlert", resourceCulture);
            }
        }
        
        internal static string ErrorDeleteHistory {
            get {
                return ResourceManager.GetString("ErrorDeleteHistory", resourceCulture);
            }
        }
        
        internal static string SucccessDeleteHistory {
            get {
                return ResourceManager.GetString("SucccessDeleteHistory", resourceCulture);
            }
        }
        
        internal static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        internal static string PermissionsStorageDeniedMessage {
            get {
                return ResourceManager.GetString("PermissionsStorageDeniedMessage", resourceCulture);
            }
        }
        
        internal static string SettingsAlwaysOnMessage {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnMessage", resourceCulture);
            }
        }
        
        internal static string SettingsAlwaysOnSubtitle {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnSubtitle", resourceCulture);
            }
        }
        
        internal static string SucccessSaveAccountFile {
            get {
                return ResourceManager.GetString("SucccessSaveAccountFile", resourceCulture);
            }
        }
        
        internal static string AckNotHelp {
            get {
                return ResourceManager.GetString("AckNotHelp", resourceCulture);
            }
        }
        
        internal static string AckSuffix {
            get {
                return ResourceManager.GetString("AckSuffix", resourceCulture);
            }
        }
        
        internal static string AckWillHelp {
            get {
                return ResourceManager.GetString("AckWillHelp", resourceCulture);
            }
        }
        
        internal static string Crash {
            get {
                return ResourceManager.GetString("Crash", resourceCulture);
            }
        }
        
        internal static string Fall {
            get {
                return ResourceManager.GetString("Fall", resourceCulture);
            }
        }
        
        internal static string FallDetectionSetting {
            get {
                return ResourceManager.GetString("FallDetectionSetting", resourceCulture);
            }
        }
        
        internal static string FallDetectionCaps {
            get {
                return ResourceManager.GetString("FallDetectionCaps", resourceCulture);
            }
        }
        
        internal static string SettingsFallDetectorMessage {
            get {
                return ResourceManager.GetString("SettingsFallDetectorMessage", resourceCulture);
            }
        }
        
        internal static string SettingsFallDetectorSubtitle {
            get {
                return ResourceManager.GetString("SettingsFallDetectorSubtitle", resourceCulture);
            }
        }
        
        internal static string CommunityRequestNotificationMessage {
            get {
                return ResourceManager.GetString("CommunityRequestNotificationMessage", resourceCulture);
            }
        }
        
        internal static string CommunityRequestNotificationTitle {
            get {
                return ResourceManager.GetString("CommunityRequestNotificationTitle", resourceCulture);
            }
        }
        
        internal static string StickNotificationGuardianButtonOpenApp {
            get {
                return ResourceManager.GetString("StickNotificationGuardianButtonOpenApp", resourceCulture);
            }
        }
        
        internal static string StickNotificationGuardianMessage {
            get {
                return ResourceManager.GetString("StickNotificationGuardianMessage", resourceCulture);
            }
        }
        
        internal static string FallDetectedSosText {
            get {
                return ResourceManager.GetString("FallDetectedSosText", resourceCulture);
            }
        }
        
        internal static string FallDetectorSettings {
            get {
                return ResourceManager.GetString("FallDetectorSettings", resourceCulture);
            }
        }
        
        internal static string FALLING_WAIST_SV_TOT {
            get {
                return ResourceManager.GetString("FALLING_WAIST_SV_TOT", resourceCulture);
            }
        }
        
        internal static string FILTER_FACTOR_0 {
            get {
                return ResourceManager.GetString("FILTER_FACTOR_0", resourceCulture);
            }
        }
        
        internal static string FILTER_FACTOR_1 {
            get {
                return ResourceManager.GetString("FILTER_FACTOR_1", resourceCulture);
            }
        }
        
        internal static string FILTER_HPF_GAIN {
            get {
                return ResourceManager.GetString("FILTER_HPF_GAIN", resourceCulture);
            }
        }
        
        internal static string FILTER_LPF_GAIN {
            get {
                return ResourceManager.GetString("FILTER_LPF_GAIN", resourceCulture);
            }
        }
        
        internal static string IMPACT_WAIST_SV_D {
            get {
                return ResourceManager.GetString("IMPACT_WAIST_SV_D", resourceCulture);
            }
        }
        
        internal static string IMPACT_WAIST_SV_MAXMIN {
            get {
                return ResourceManager.GetString("IMPACT_WAIST_SV_MAXMIN", resourceCulture);
            }
        }
        
        internal static string IMPACT_WAIST_SV_TOT {
            get {
                return ResourceManager.GetString("IMPACT_WAIST_SV_TOT", resourceCulture);
            }
        }
        
        internal static string IMPACT_WAIST_Z_2 {
            get {
                return ResourceManager.GetString("IMPACT_WAIST_Z_2", resourceCulture);
            }
        }
        
        internal static string INTERVAL_MS {
            get {
                return ResourceManager.GetString("INTERVAL_MS", resourceCulture);
            }
        }
        
        internal static string LYING_AVERAGE_Z_LPF {
            get {
                return ResourceManager.GetString("LYING_AVERAGE_Z_LPF", resourceCulture);
            }
        }
        
        internal static string FillAllDetectorValues {
            get {
                return ResourceManager.GetString("FillAllDetectorValues", resourceCulture);
            }
        }
        
        internal static string SettingUpdateProfle {
            get {
                return ResourceManager.GetString("SettingUpdateProfle", resourceCulture);
            }
        }
        
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        internal static string MSG {
            get {
                return ResourceManager.GetString("MSG", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string TouristGuide {
            get {
                return ResourceManager.GetString("TouristGuide", resourceCulture);
            }
        }
        
        internal static string SubscriptionStatusOK {
            get {
                return ResourceManager.GetString("SubscriptionStatusOK", resourceCulture);
            }
        }
        
        internal static string SubscriptionStatusInactive {
            get {
                return ResourceManager.GetString("SubscriptionStatusInactive", resourceCulture);
            }
        }
        
        internal static string NoSubscription {
            get {
                return ResourceManager.GetString("NoSubscription", resourceCulture);
            }
        }
        
        internal static string SubscriptionStatusExpiring {
            get {
                return ResourceManager.GetString("SubscriptionStatusExpiring", resourceCulture);
            }
        }
        
        internal static string SubscriptionStatusExpired {
            get {
                return ResourceManager.GetString("SubscriptionStatusExpired", resourceCulture);
            }
        }
        
        internal static string SubscriptionStart {
            get {
                return ResourceManager.GetString("SubscriptionStart", resourceCulture);
            }
        }
        
        internal static string SubscriptionPackage {
            get {
                return ResourceManager.GetString("SubscriptionPackage", resourceCulture);
            }
        }
        
        internal static string NoSubscriptionInfo {
            get {
                return ResourceManager.GetString("NoSubscriptionInfo", resourceCulture);
            }
        }
        
        internal static string SubscriptionFrame {
            get {
                return ResourceManager.GetString("SubscriptionFrame", resourceCulture);
            }
        }
        
        internal static string SubscriptionEnd {
            get {
                return ResourceManager.GetString("SubscriptionEnd", resourceCulture);
            }
        }
        
        internal static string SingleContact {
            get {
                return ResourceManager.GetString("SingleContact", resourceCulture);
            }
        }
        
        internal static string NoContactsNoSub {
            get {
                return ResourceManager.GetString("NoContactsNoSub", resourceCulture);
            }
        }
        
        internal static string AddSub {
            get {
                return ResourceManager.GetString("AddSub", resourceCulture);
            }
        }
        
        internal static string SubscriptionPage {
            get {
                return ResourceManager.GetString("SubscriptionPage", resourceCulture);
            }
        }
        
        internal static string CanYouHelp {
            get {
                return ResourceManager.GetString("CanYouHelp", resourceCulture);
            }
        }
        
        internal static string SwitchSOS {
            get {
                return ResourceManager.GetString("SwitchSOS", resourceCulture);
            }
        }
        
        internal static string SwitchSubscription {
            get {
                return ResourceManager.GetString("SwitchSubscription", resourceCulture);
            }
        }
        
        internal static string SwitchMap {
            get {
                return ResourceManager.GetString("SwitchMap", resourceCulture);
            }
        }
        
        internal static string SettingChangeSOS {
            get {
                return ResourceManager.GetString("SettingChangeSOS", resourceCulture);
            }
        }
        
        internal static string SwitchSOSLbl {
            get {
                return ResourceManager.GetString("SwitchSOSLbl", resourceCulture);
            }
        }
        
        internal static string RemoveUserAnalytical {
            get {
                return ResourceManager.GetString("RemoveUserAnalytical", resourceCulture);
            }
        }
        
        internal static string PendingRequestsPage {
            get {
                return ResourceManager.GetString("PendingRequestsPage", resourceCulture);
            }
        }
        
        internal static string DoNotShowSetting {
            get {
                return ResourceManager.GetString("DoNotShowSetting", resourceCulture);
            }
        }
        
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        internal static string SuccessSendAlertMessageSrc {
            get {
                return ResourceManager.GetString("SuccessSendAlertMessageSrc", resourceCulture);
            }
        }
        
        internal static string InformUserPhoneNumber {
            get {
                return ResourceManager.GetString("InformUserPhoneNumber", resourceCulture);
            }
        }
    }
}
